version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14
    container_name: rideshare_postgres
    environment:
      POSTGRES_DB: rideshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.3-python3.10
    platform: linux/arm64
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - "AIRFLOW__CORE__EXECUTOR=SequentialExecutor"
      - "AIRFLOW__CORE__FERNET_KEY=YOUR_SECRET_KEY"
      - "AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False"
      - "AIRFLOW__CORE__LOAD_EXAMPLES=False"
    volumes:
      - ./airflow_dags:/opt/airflow/dags
    depends_on:
      - postgres

volumes:
  pgdata: